version: "2"
services:
  resilio:
    network_mode: "host"
    image: elcrp96/resilio-sync:latest
    environment:
      - PUID=998
      - PGID=994
      - TZ=Europe/London
    ports:
      - "8888:8888"
      - "55555:55555"
    volumes:
      - "/mnt/storage/local/resilio/config.json:/etc/rslsync/config.json"
      - "/mnt/storage/local/resilio/rslsync.log:/var/log/rslsync.log"
      - "/mnt/storage/sync/:/downloads/"
      - "/mnt/storage/local/resilio:/resilio/"
    restart: always
