version: "3.7"
services:
  resilio:
    container_name: resilio
    network_mode: "host"
    image: elcrp96/resilio-sync:latest
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
      - dotENV
    ports:
      - "8888:8888"
      - "55555:55555"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/mnt/storage/local/resilio/config.json:/config/sync.json"
      - "/mnt/storage/local/resilio/rslsync.log:/var/log/rslsync.log"
      - "/mnt/storage/local/resilio:/resilio/"
      - "/mnt/storage/sync/:/downloads/"
    restart: unless-stopped
